### ISSUE TITLE
CamVid-30K dataset release time

### ISSUE THREAD

**Issue by Yujie-G** [HeliosZhao/GenXD#1]
Could you share any updates on when the dataset and model might be available? thx

**Comment by HeliosZhao** [comment]
Hi @Yujie-G! Thanks for your interest. We will try to release them in November.

**Comment by zhw-zhang** [comment]
Hi, I noticed that during training, videos with a resolution of 256x256 are used. Could you please let me know if the CamVid-30K dataset also only has a resolution of 256x256? Or do the videos have a higher resolution, and you resized them during training? Thank you!

**Comment by HeliosZhao** [comment]
We resize the shorter edge to 256 when processing CamVid-30K, and make the video square with center crop or zero padding to train diffusion model. Therefore, we do not have a higher resolution data.

**Comment by zhw-zhang** [comment]
Thanks for your reply. I'm curious why you chose a resolution of 256x256 when constructing the video dataset. Even for video generation, this resolution seems a bit low. Is it because some steps in the data generation pipeline are particularly time-consuming? Looking forward to having higher resolution datasets in the future, which will greatly increase the usage scenarios of this dataset.  Additionally, I would be interested to know the typical resolution of the videos' longer side in the original dataset.

**Comment by HeliosZhao** [comment]
Good point. The reason why we choose 256x256 is simple: we do not have enough gpus :). We can use 4 samples per batch with 256x256 but can only one with 512x512. Therefore, we just resize the shorter edge of the videos to 256 to save storage memory when constructing data. We may consider annotating 4D data with higher resolution in the future.

As for the original resolution of the videos, you can refer to the video datasets we use ([VIPSeg](https://github.com/VIPSeg-Dataset/VIPSeg-Dataset), [OpenVid-1M](https://github.com/NJU-PCALab/OpenVid-1M), and [Webvid-10M](https://github.com/m-bain/webvid)).

**Comment by zhw-zhang** [comment]
Thank you for your reply — I understand now. I really appreciate that you will make the dataset open-source; I believe this will be a key factor in making your paper even more impactful than others in the field.

**Comment by stuartjing** [comment]
@HeliosZhao  This is a great project. Do we have a specific release date for the dataset

**Comment by zhw-zhang** [comment]
hi, any update?

**Comment by HeliosZhao** [comment]
Hi all, thanks for waiting! The dataset has been released.

**Comment by yaojin17** [comment]
@HeliosZhao, thanks for your awesome work on open-sourcing the dataset! May I ask if a dense depth map for every frame is included in the open-sourced dataset files?

**Comment by HeliosZhao** [comment]
> @HeliosZhao, thanks for your awesome work on open-sourcing the dataset! May I ask if a dense depth map for every frame is included in the open-sourced dataset files?

Nope, the depth maps are not included in the released data file. The depth maps are obtained via Depth Anything V2 and aligned with the COLMAP projected depth. Since the COLMAP source files are released, you can obtain the depth maps your self. 

We may provide the depth alignment python script in the future.
